---
- name: Restart headscale service
  ansible.builtin.systemd:
    name: headscale
    state: restarted
    enabled: true
    daemon-reload: true
  listen: 'restart headscale'

- name: Reload headscale
  ansible.builtin.systemd:
    name: headscale
    state: reloaded
  listen: 'reload headscale'
